### ISSUE TITLE
Default arguments in sh-Branch doesn't fit to 'default' marytts download

### ISSUE THREAD

**Issue by YggdrasiI** [marytts/marytts-txt2wav#9]
Hello,

the runtime packages of Mary 5.2 on http://mary.dfki.de/download/ does not contain the German voice, used in the 'sh' branch. As the curl request in this script does not return any error message, but an empty reply it is not obvious why the script do not work.

I would suggest to change the lines 
```
lang='de'
voice='dfki-pavoque-styles'
```
to
```
lang='en_US'
voice='cmu-slt-hsmm'
```

**Comment by seblemaguer** [comment]
Hello,

thanks you are completely correct :) I update this.
